const types =
{
  SET_USERINFO: 'SET_USERINFO',
  GET_USERINFO: 'GET_USERINFO',
  MODIFY_REM: 'MODIFY_REM',
  GET_REM: 'GET_REM',
  SET_TRANSLATE:'SET_TRANSLATE',
  GET_TRANSLATE:'GET_TRANSLATE',
  SET_MASKOPACITY:'SET_MASKOPACITY',
  GET_MASKOPACITY:'GET_MASKOPACITY'
};

export default types
